// <auto-generated />
using System;
using D.Ceylon.Modules.ItinerariesTravelPlanning.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace D.Ceylon.Modules.ItinerariesTravelPlanning.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ItinerariesTravelPlanningDbContext))]
    [Migration("20260728075115_AddDeterministicTravelPlanning")]
    partial class AddDeterministicTravelPlanning
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("itineraries_travel_planning")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.ItineraryDay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("day_number");

                    b.Property<Guid>("ItineraryRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("itinerary_revision_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryRevisionId", "DayNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_itinerary_days_revision_order");

                    b.ToTable("itinerary_days", "itineraries_travel_planning");
                });

            modelBuilder.Entity("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.ItineraryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DestinationSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("destination_slug");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<Guid>("ItineraryDayId")
                        .HasColumnType("uuid")
                        .HasColumnName("itinerary_day_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("ProductSlug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_slug");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("DestinationSlug")
                        .HasDatabaseName("ix_itinerary_items_destination_slug");

                    b.HasIndex("ProductSlug")
                        .HasDatabaseName("ix_itinerary_items_product_slug");

                    b.HasIndex("ItineraryDayId", "Position")
                        .HasDatabaseName("ix_itinerary_items_day_order");

                    b.ToTable("itinerary_items", "itineraries_travel_planning");
                });

            modelBuilder.Entity("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.ItineraryRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at_utc");

                    b.Property<string>("InputFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("input_fingerprint");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_version");

                    b.Property<Guid>("TravelPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("travel_plan_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("TravelPlanId", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_itinerary_revisions_plan_number");

                    b.ToTable("itinerary_revisions", "itineraries_travel_planning");
                });

            modelBuilder.Entity("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.TravelPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessibilityConsiderations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("accessibility_considerations");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CurrentRevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("current_revision_number");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("DietaryConsiderations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("dietary_considerations");

                    b.Property<string>("InputFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("input_fingerprint");

                    b.Property<string>("Pace")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pace");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_version");

                    b.Property<Guid?>("SavedItineraryId")
                        .HasColumnType("uuid")
                        .HasColumnName("saved_itinerary_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateOnly>("TravelEndDate")
                        .HasColumnType("date")
                        .HasColumnName("travel_end_date");

                    b.Property<DateOnly>("TravelStartDate")
                        .HasColumnType("date")
                        .HasColumnName("travel_start_date");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "SavedItineraryId")
                        .HasDatabaseName("ix_travel_plans_customer_saved_itinerary");

                    b.HasIndex("RuleVersion", "InputFingerprint")
                        .HasDatabaseName("ix_travel_plans_rule_fingerprint");

                    b.HasIndex("CustomerId", "Status", "UpdatedAtUtc")
                        .HasDatabaseName("ix_travel_plans_customer_status_updated");

                    b.ToTable("travel_plans", "itineraries_travel_planning", t =>
                        {
                            t.HasCheckConstraint("ck_travel_plans_dates", "travel_end_date >= travel_start_date AND travel_end_date - travel_start_date <= 29");
                        });
                });

            modelBuilder.Entity("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.TravelPlanDestination", b =>
                {
                    b.Property<Guid>("TravelPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("travel_plan_id");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("destination_slug");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("TravelPlanId", "Slug");

                    b.HasIndex("Slug")
                        .HasDatabaseName("ix_travel_plan_destinations_slug");

                    b.HasIndex("TravelPlanId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_travel_plan_destinations_order");

                    b.ToTable("travel_plan_destinations", "itineraries_travel_planning");
                });

            modelBuilder.Entity("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.TravelPlanInterest", b =>
                {
                    b.Property<Guid>("TravelPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("travel_plan_id");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("interest_slug");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("TravelPlanId", "Slug");

                    b.ToTable("travel_plan_interests", "itineraries_travel_planning");
                });

            modelBuilder.Entity("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.TravelPlanPreference", b =>
                {
                    b.Property<Guid>("TravelPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("travel_plan_id");

                    b.Property<string>("Kind")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("TravelPlanId", "Kind", "Slug");

                    b.HasIndex("Kind", "Slug")
                        .HasDatabaseName("ix_travel_plan_preferences_lookup");

                    b.ToTable("travel_plan_preferences", "itineraries_travel_planning");
                });

            modelBuilder.Entity("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.TravelPlanTraveller", b =>
                {
                    b.Property<Guid>("TravelPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("travel_plan_id");

                    b.Property<Guid>("TravellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveller_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("TravelPlanId", "TravellerId");

                    b.HasIndex("TravellerId")
                        .HasDatabaseName("ix_travel_plan_travellers_traveller");

                    b.ToTable("travel_plan_travellers", "itineraries_travel_planning");
                });

            modelBuilder.Entity("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.ItineraryDay", b =>
                {
                    b.HasOne("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.ItineraryRevision", null)
                        .WithMany("Days")
                        .HasForeignKey("ItineraryRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.ItineraryItem", b =>
                {
                    b.HasOne("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.ItineraryDay", null)
                        .WithMany("Items")
                        .HasForeignKey("ItineraryDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.ItineraryRevision", b =>
                {
                    b.HasOne("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.TravelPlan", null)
                        .WithMany("Revisions")
                        .HasForeignKey("TravelPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.TravelPlanDestination", b =>
                {
                    b.HasOne("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.TravelPlan", null)
                        .WithMany("Destinations")
                        .HasForeignKey("TravelPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.TravelPlanInterest", b =>
                {
                    b.HasOne("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.TravelPlan", null)
                        .WithMany("Interests")
                        .HasForeignKey("TravelPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.TravelPlanPreference", b =>
                {
                    b.HasOne("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.TravelPlan", null)
                        .WithMany("Preferences")
                        .HasForeignKey("TravelPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.TravelPlanTraveller", b =>
                {
                    b.HasOne("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.TravelPlan", null)
                        .WithMany("Travellers")
                        .HasForeignKey("TravelPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.ItineraryDay", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.ItineraryRevision", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("D.Ceylon.Modules.ItinerariesTravelPlanning.Domain.TravelPlan", b =>
                {
                    b.Navigation("Destinations");

                    b.Navigation("Interests");

                    b.Navigation("Preferences");

                    b.Navigation("Revisions");

                    b.Navigation("Travellers");
                });
#pragma warning restore 612, 618
        }
    }
}
