export {
  ApiRequestError,
  createCatalogueClient,
  type CatalogueClient,
  type CatalogueClientOptions,
  type CataloguePagination,
  type CatalogueSearch,
  type CataloguePage,
  type CollectionDetail,
  type CollectionPage,
  type CollectionSummary,
  type DestinationDetail,
  type DestinationPage,
  type DestinationSummary,
  type NamedReference,
  type ProductDetail,
  type ProductSummary,
  type ProductType,
} from "./catalogue-client";
