// <auto-generated />
using System;
using D.Ceylon.Modules.Catalogue.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace D.Ceylon.Modules.Catalogue.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogueDbContext))]
    partial class CatalogueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalogue")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("D.Ceylon.Modules.Catalogue.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_categories_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_categories_slug");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("ix_categories_updated_at_utc");

                    b.ToTable("categories", "catalogue");
                });

            modelBuilder.Entity("D.Ceylon.Modules.Catalogue.Domain.Destination", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_destinations_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_destinations_slug");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("ix_destinations_updated_at_utc");

                    b.ToTable("destinations", "catalogue");
                });

            modelBuilder.Entity("D.Ceylon.Modules.Catalogue.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_type_id");

                    b.Property<string>("PublicationState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("publication_state");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_description");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<decimal?>("StartingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("starting_price");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_products_name");

                    b.HasIndex("ProductTypeId")
                        .HasDatabaseName("ix_products_product_type_id");

                    b.HasIndex("PublicationState")
                        .HasDatabaseName("ix_products_publication_state");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_products_slug");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("ix_products_updated_at_utc");

                    b.ToTable("products", "catalogue", t =>
                        {
                            t.HasCheckConstraint("ck_products_currency", "char_length(currency) = 3");

                            t.HasCheckConstraint("ck_products_duration", "duration_minutes IS NULL OR duration_minutes > 0");

                            t.HasCheckConstraint("ck_products_starting_price", "starting_price IS NULL OR starting_price >= 0");
                        });
                });

            modelBuilder.Entity("D.Ceylon.Modules.Catalogue.Domain.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_product_categories_category_id");

                    b.ToTable("product_categories", "catalogue");
                });

            modelBuilder.Entity("D.Ceylon.Modules.Catalogue.Domain.ProductCollectionLink", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.HasKey("ProductId", "CollectionId");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("ix_product_collections_collection_id");

                    b.ToTable("product_collections", "catalogue");
                });

            modelBuilder.Entity("D.Ceylon.Modules.Catalogue.Domain.ProductDestination", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_id");

                    b.HasKey("ProductId", "DestinationId");

                    b.HasIndex("DestinationId")
                        .HasDatabaseName("ix_product_destinations_destination_id");

                    b.ToTable("product_destinations", "catalogue");
                });

            modelBuilder.Entity("D.Ceylon.Modules.Catalogue.Domain.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_product_types_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_product_types_slug");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("ix_product_types_updated_at_utc");

                    b.ToTable("product_types", "catalogue");
                });

            modelBuilder.Entity("D.Ceylon.Modules.Catalogue.Domain.TravelCollectionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_collections_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_collections_slug");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("ix_collections_updated_at_utc");

                    b.ToTable("collections", "catalogue");
                });

            modelBuilder.Entity("D.Ceylon.Modules.Catalogue.Domain.Product", b =>
                {
                    b.HasOne("D.Ceylon.Modules.Catalogue.Domain.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("D.Ceylon.Modules.Catalogue.Domain.ProductCategory", b =>
                {
                    b.HasOne("D.Ceylon.Modules.Catalogue.Domain.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("D.Ceylon.Modules.Catalogue.Domain.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("D.Ceylon.Modules.Catalogue.Domain.ProductCollectionLink", b =>
                {
                    b.HasOne("D.Ceylon.Modules.Catalogue.Domain.TravelCollectionEntry", "Collection")
                        .WithMany("ProductCollections")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("D.Ceylon.Modules.Catalogue.Domain.Product", "Product")
                        .WithMany("ProductCollections")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("D.Ceylon.Modules.Catalogue.Domain.ProductDestination", b =>
                {
                    b.HasOne("D.Ceylon.Modules.Catalogue.Domain.Destination", "Destination")
                        .WithMany("ProductDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("D.Ceylon.Modules.Catalogue.Domain.Product", "Product")
                        .WithMany("ProductDestinations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("D.Ceylon.Modules.Catalogue.Domain.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("D.Ceylon.Modules.Catalogue.Domain.Destination", b =>
                {
                    b.Navigation("ProductDestinations");
                });

            modelBuilder.Entity("D.Ceylon.Modules.Catalogue.Domain.Product", b =>
                {
                    b.Navigation("ProductCategories");

                    b.Navigation("ProductCollections");

                    b.Navigation("ProductDestinations");
                });

            modelBuilder.Entity("D.Ceylon.Modules.Catalogue.Domain.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("D.Ceylon.Modules.Catalogue.Domain.TravelCollectionEntry", b =>
                {
                    b.Navigation("ProductCollections");
                });
#pragma warning restore 612, 618
        }
    }
}
