// <auto-generated />
using System;
using D.Ceylon.Modules.Quotes.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace D.Ceylon.Modules.Quotes.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(QuotesDbContext))]
    [Migration("20260728092831_AddQuoteWorkflow")]
    partial class AddQuoteWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("quotes")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("D.Ceylon.Modules.Quotes.Domain.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("CurrentExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_expires_at_utc");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_version_id");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("current_version_number");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.PrimitiveCollection<string[]>("DraftAssumptions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("draft_assumptions");

                    b.PrimitiveCollection<string[]>("DraftExclusions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("draft_exclusions");

                    b.PrimitiveCollection<string[]>("DraftInclusions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("draft_inclusions");

                    b.Property<string>("DraftTerms")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("draft_terms");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("internal_notes");

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ux_quotes_request");

                    b.HasIndex("Status", "CurrentExpiresAtUtc")
                        .HasDatabaseName("ix_quotes_status_expiry");

                    b.HasIndex("CustomerId", "Status", "UpdatedAtUtc")
                        .HasDatabaseName("ix_quotes_customer_status_updated");

                    b.HasIndex("OrganisationId", "Status", "UpdatedAtUtc")
                        .HasDatabaseName("ix_quotes_organisation_status_updated");

                    b.ToTable("quotes", "quotes", t =>
                        {
                            t.HasCheckConstraint("ck_quotes_currency", "currency IS NULL OR currency IN ('EUR','GBP','LKR','USD')");

                            t.HasCheckConstraint("ck_quotes_status", "status IN ('draft','sent','accepted','declined','expired','withdrawn')");
                        });
                });

            modelBuilder.Entity("D.Ceylon.Modules.Quotes.Domain.QuoteDraftLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<decimal>("UnitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_amount");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_quote_draft_lines_order");

                    b.ToTable("quote_draft_lines", "quotes", t =>
                        {
                            t.HasCheckConstraint("ck_quote_draft_lines_quantity", "quantity > 0 AND quantity <= 1000");

                            t.HasCheckConstraint("ck_quote_draft_lines_unit_amount", "unit_amount >= 0 AND unit_amount <= 99999999.99");
                        });
                });

            modelBuilder.Entity("D.Ceylon.Modules.Quotes.Domain.QuoteDraftPriceComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_quote_draft_components_order");

                    b.ToTable("quote_draft_price_components", "quotes", t =>
                        {
                            t.HasCheckConstraint("ck_quote_draft_components_amount", "amount >= -99999999.99 AND amount <= 99999999.99");

                            t.HasCheckConstraint("ck_quote_draft_components_kind", "kind IN ('tax','adjustment')");
                        });
                });

            modelBuilder.Entity("D.Ceylon.Modules.Quotes.Domain.QuoteRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("customer_notes");

                    b.Property<string>("ItineraryFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("itinerary_fingerprint");

                    b.Property<Guid>("ItineraryRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("itinerary_revision_id");

                    b.Property<int>("ItineraryRevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("itinerary_revision_number");

                    b.Property<string>("ItineraryTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("itinerary_title");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_version");

                    b.Property<DateOnly>("TravelEndDate")
                        .HasColumnType("date")
                        .HasColumnName("travel_end_date");

                    b.Property<Guid>("TravelPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("travel_plan_id");

                    b.Property<DateOnly>("TravelStartDate")
                        .HasColumnType("date")
                        .HasColumnName("travel_start_date");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("TravelPlanId")
                        .HasDatabaseName("ix_quote_requests_travel_plan");

                    b.HasIndex("CustomerId", "ItineraryRevisionId")
                        .IsUnique()
                        .HasDatabaseName("ux_quote_requests_customer_revision");

                    b.ToTable("quote_requests", "quotes", t =>
                        {
                            t.HasCheckConstraint("ck_quote_requests_dates", "travel_end_date >= travel_start_date");
                        });
                });

            modelBuilder.Entity("D.Ceylon.Modules.Quotes.Domain.QuoteVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AdjustmentTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("adjustment_total");

                    b.PrimitiveCollection<string[]>("Assumptions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("assumptions");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBySubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by_subject");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.PrimitiveCollection<string[]>("Exclusions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("exclusions");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("grand_total");

                    b.PrimitiveCollection<string[]>("Inclusions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("inclusions");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<DateTimeOffset>("SentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at_utc");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TaxTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax_total");

                    b.Property<string>("Terms")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("terms");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_quote_versions_expiry");

                    b.HasIndex("QuoteId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_quote_versions_quote_number");

                    b.ToTable("quote_versions", "quotes", t =>
                        {
                            t.HasCheckConstraint("ck_quote_versions_currency", "currency IN ('EUR','GBP','LKR','USD')");

                            t.HasCheckConstraint("ck_quote_versions_expiry", "expires_at_utc > sent_at_utc");

                            t.HasCheckConstraint("ck_quote_versions_totals", "subtotal >= 0 AND tax_total >= 0 AND grand_total >= 0");
                        });
                });

            modelBuilder.Entity("D.Ceylon.Modules.Quotes.Domain.QuoteVersionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("line_total");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("QuoteVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_version_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<decimal>("UnitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_amount");

                    b.HasKey("Id");

                    b.HasIndex("QuoteVersionId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_quote_version_lines_order");

                    b.ToTable("quote_version_lines", "quotes");
                });

            modelBuilder.Entity("D.Ceylon.Modules.Quotes.Domain.QuoteVersionPriceComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("QuoteVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_version_id");

                    b.HasKey("Id");

                    b.HasIndex("QuoteVersionId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_quote_version_components_order");

                    b.ToTable("quote_version_price_components", "quotes");
                });

            modelBuilder.Entity("D.Ceylon.Modules.Quotes.Domain.Quote", b =>
                {
                    b.HasOne("D.Ceylon.Modules.Quotes.Domain.QuoteRequest", "Request")
                        .WithOne("Quote")
                        .HasForeignKey("D.Ceylon.Modules.Quotes.Domain.Quote", "RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("D.Ceylon.Modules.Quotes.Domain.QuoteDraftLine", b =>
                {
                    b.HasOne("D.Ceylon.Modules.Quotes.Domain.Quote", null)
                        .WithMany("DraftLines")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("D.Ceylon.Modules.Quotes.Domain.QuoteDraftPriceComponent", b =>
                {
                    b.HasOne("D.Ceylon.Modules.Quotes.Domain.Quote", null)
                        .WithMany("DraftComponents")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("D.Ceylon.Modules.Quotes.Domain.QuoteVersion", b =>
                {
                    b.HasOne("D.Ceylon.Modules.Quotes.Domain.Quote", null)
                        .WithMany("Versions")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("D.Ceylon.Modules.Quotes.Domain.QuoteVersionLine", b =>
                {
                    b.HasOne("D.Ceylon.Modules.Quotes.Domain.QuoteVersion", null)
                        .WithMany("Lines")
                        .HasForeignKey("QuoteVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("D.Ceylon.Modules.Quotes.Domain.QuoteVersionPriceComponent", b =>
                {
                    b.HasOne("D.Ceylon.Modules.Quotes.Domain.QuoteVersion", null)
                        .WithMany("Components")
                        .HasForeignKey("QuoteVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("D.Ceylon.Modules.Quotes.Domain.Quote", b =>
                {
                    b.Navigation("DraftComponents");

                    b.Navigation("DraftLines");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("D.Ceylon.Modules.Quotes.Domain.QuoteRequest", b =>
                {
                    b.Navigation("Quote")
                        .IsRequired();
                });

            modelBuilder.Entity("D.Ceylon.Modules.Quotes.Domain.QuoteVersion", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
