from typing import Protocol


class ApprovedBackendTools(Protocol):
    """Future backend-mediated tools. They must enforce caller authorisation themselves."""

    async def search_products(self) -> None: ...
    async def search_destinations(self) -> None: ...
    async def check_route_constraints(self) -> None: ...
    async def build_draft_itinerary(self) -> None: ...
    async def estimate_quote_range(self) -> None: ...
    async def save_draft_itinerary(self) -> None: ...
    async def request_human_quote(self) -> None: ...
