<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks\D.Ceylon.BuildingBlocks\D.Ceylon.BuildingBlocks.csproj" />
    <ProjectReference Include="..\Modules\Bookings\D.Ceylon.Modules.Bookings\D.Ceylon.Modules.Bookings.csproj" />
    <ProjectReference Include="..\Modules\Payments\D.Ceylon.Modules.Payments\D.Ceylon.Modules.Payments.csproj" />
    <ProjectReference Include="..\Modules\Catalogue\D.Ceylon.Modules.Catalogue\D.Ceylon.Modules.Catalogue.csproj" />
    <ProjectReference Include="..\Modules\CustomersTravellers\D.Ceylon.Modules.CustomersTravellers\D.Ceylon.Modules.CustomersTravellers.csproj" />
    <ProjectReference Include="..\Modules\Editorial\D.Ceylon.Modules.Editorial\D.Ceylon.Modules.Editorial.csproj" />
    <ProjectReference Include="..\Modules\IdentityAccess\D.Ceylon.Modules.IdentityAccess\D.Ceylon.Modules.IdentityAccess.csproj" />
    <ProjectReference Include="..\Modules\ItinerariesTravelPlanning\D.Ceylon.Modules.ItinerariesTravelPlanning\D.Ceylon.Modules.ItinerariesTravelPlanning.csproj" />
    <ProjectReference Include="..\Modules\OrganisationsAgents\D.Ceylon.Modules.OrganisationsAgents\D.Ceylon.Modules.OrganisationsAgents.csproj" />
    <ProjectReference Include="..\Modules\Quotes\D.Ceylon.Modules.Quotes\D.Ceylon.Modules.Quotes.csproj" />
    <ProjectReference Include="..\Modules\SupplierOperations\D.Ceylon.Modules.SupplierOperations\D.Ceylon.Modules.SupplierOperations.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
</Project>
