// <auto-generated />
using System;
using D.Ceylon.Modules.Payments.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace D.Ceylon.Modules.Payments.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    [Migration("20260728110100_AddPaymentWorkflow")]
    partial class AddPaymentWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payments")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("D.Ceylon.Modules.Payments.Domain.Payment", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
                b.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnName("amount").HasColumnType("numeric(18,2)");
                b.Property<Guid>("BookingId").HasColumnName("booking_id").HasColumnType("uuid");
                b.Property<DateTimeOffset?>("CapturedAtUtc").HasColumnName("captured_at_utc").HasColumnType("timestamp with time zone");
                b.Property<Guid>("ConcurrencyToken").IsConcurrencyToken().HasColumnName("concurrency_token").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnName("created_at_utc").HasColumnType("timestamp with time zone");
                b.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnName("currency").HasColumnType("character varying(3)");
                b.Property<Guid>("CustomerId").HasColumnName("customer_id").HasColumnType("uuid");
                b.Property<string>("FailedReason").HasMaxLength(500).HasColumnName("failed_reason").HasColumnType("character varying(500)");
                b.Property<string>("Gateway").IsRequired().HasMaxLength(30).HasColumnName("gateway").HasColumnType("character varying(30)");
                b.Property<string>("IdempotencyKey").IsRequired().HasMaxLength(64).HasColumnName("idempotency_key").HasColumnType("character varying(64)");
                b.Property<string>("Kind").IsRequired().HasMaxLength(30).HasColumnName("kind").HasColumnType("character varying(30)");
                b.Property<DateTimeOffset?>("PaymentLinkExpiresAtUtc").HasColumnName("payment_link_expires_at_utc").HasColumnType("timestamp with time zone");
                b.Property<string>("PaymentLinkUrl").HasMaxLength(500).HasColumnName("payment_link_url").HasColumnType("character varying(500)");
                b.Property<string>("ReconciliationStatus").IsRequired().HasMaxLength(20).HasColumnName("reconciliation_status").HasColumnType("character varying(20)");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnName("status").HasColumnType("character varying(20)");
                b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnName("updated_at_utc").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("IdempotencyKey").IsUnique().HasDatabaseName("ux_payments_idempotency_key");
                b.HasIndex("CustomerId", "BookingId", "Status").HasDatabaseName("ix_payments_customer_booking_status");
                b.HasIndex("BookingId", "Status").HasDatabaseName("ix_payments_booking_status");
                b.HasIndex("ReconciliationStatus", "Status").HasDatabaseName("ix_payments_reconciliation_status");
                b.ToTable("payments", "payments", t =>
                {
                    t.HasCheckConstraint("ck_payments_amount", "amount > 0 AND amount <= 99999999.99");
                    t.HasCheckConstraint("ck_payments_currency", "currency IN ('EUR','GBP','LKR','USD')");
                    t.HasCheckConstraint("ck_payments_gateway", "gateway IN ('stripe','local','manual')");
                    t.HasCheckConstraint("ck_payments_kind", "kind IN ('deposit','balance','manual-transfer','payment-link')");
                    t.HasCheckConstraint("ck_payments_reconciliation", "reconciliation_status IN ('unreconciled','reconciled','disputed')");
                    t.HasCheckConstraint("ck_payments_status", "status IN ('pending','authorised','captured','failed','refunded','cancelled')");
                });
            });

            modelBuilder.Entity("D.Ceylon.Modules.Payments.Domain.PaymentTransaction", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
                b.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnName("amount").HasColumnType("numeric(18,2)");
                b.Property<Guid>("ConcurrencyToken").IsConcurrencyToken().HasColumnName("concurrency_token").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnName("created_at_utc").HasColumnType("timestamp with time zone");
                b.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnName("currency").HasColumnType("character varying(3)");
                b.Property<string>("EventType").IsRequired().HasMaxLength(50).HasColumnName("event_type").HasColumnType("character varying(50)");
                b.Property<string>("Gateway").IsRequired().HasMaxLength(30).HasColumnName("gateway").HasColumnType("character varying(30)");
                b.Property<string>("GatewayReference").IsRequired().HasMaxLength(200).HasColumnName("gateway_reference").HasColumnType("character varying(200)");
                b.Property<DateTimeOffset>("OccurredAtUtc").HasColumnName("occurred_at_utc").HasColumnType("timestamp with time zone");
                b.Property<Guid>("PaymentId").HasColumnName("payment_id").HasColumnType("uuid");
                b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnName("updated_at_utc").HasColumnType("timestamp with time zone");
                b.Property<bool>("WebhookSignatureVerified").HasColumnName("webhook_signature_verified").HasColumnType("boolean");
                b.HasKey("Id");
                b.HasIndex("PaymentId", "OccurredAtUtc").HasDatabaseName("ix_payment_transactions_payment_occurred");
                b.HasIndex("GatewayReference").HasDatabaseName("ix_payment_transactions_gateway_reference");
                b.ToTable("payment_transactions", "payments", t =>
                {
                    t.HasCheckConstraint("ck_payment_transactions_currency", "currency IN ('EUR','GBP','LKR','USD')");
                    t.HasCheckConstraint("ck_payment_transactions_gateway", "gateway IN ('stripe','local','manual')");
                });
            });

            modelBuilder.Entity("D.Ceylon.Modules.Payments.Domain.Refund", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
                b.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnName("amount").HasColumnType("numeric(18,2)");
                b.Property<string>("ApprovedBySubject").HasMaxLength(200).HasColumnName("approved_by_subject").HasColumnType("character varying(200)");
                b.Property<Guid>("ConcurrencyToken").IsConcurrencyToken().HasColumnName("concurrency_token").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnName("created_at_utc").HasColumnType("timestamp with time zone");
                b.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnName("currency").HasColumnType("character varying(3)");
                b.Property<string>("GatewayReference").HasMaxLength(200).HasColumnName("gateway_reference").HasColumnType("character varying(200)");
                b.Property<string>("IdempotencyKey").IsRequired().HasMaxLength(64).HasColumnName("idempotency_key").HasColumnType("character varying(64)");
                b.Property<string>("InitiatedBySubject").IsRequired().HasMaxLength(200).HasColumnName("initiated_by_subject").HasColumnType("character varying(200)");
                b.Property<Guid>("PaymentId").HasColumnName("payment_id").HasColumnType("uuid");
                b.Property<string>("Reason").HasMaxLength(500).HasColumnName("reason").HasColumnType("character varying(500)");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnName("status").HasColumnType("character varying(20)");
                b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnName("updated_at_utc").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("IdempotencyKey").IsUnique().HasDatabaseName("ux_refunds_idempotency_key");
                b.HasIndex("PaymentId", "Status").HasDatabaseName("ix_refunds_payment_status");
                b.ToTable("refunds", "payments", t =>
                {
                    t.HasCheckConstraint("ck_refunds_amount", "amount > 0 AND amount <= 99999999.99");
                    t.HasCheckConstraint("ck_refunds_currency", "currency IN ('EUR','GBP','LKR','USD')");
                    t.HasCheckConstraint("ck_refunds_status", "status IN ('pending','succeeded','failed')");
                });
            });

            modelBuilder.Entity("D.Ceylon.Modules.Payments.Domain.PaymentTransaction", b =>
            {
                b.HasOne("D.Ceylon.Modules.Payments.Domain.Payment", null)
                    .WithMany("Transactions")
                    .HasForeignKey("PaymentId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("D.Ceylon.Modules.Payments.Domain.Refund", b =>
            {
                b.HasOne("D.Ceylon.Modules.Payments.Domain.Payment", null)
                    .WithMany("Refunds")
                    .HasForeignKey("PaymentId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("D.Ceylon.Modules.Payments.Domain.Payment", b =>
            {
                b.Navigation("Transactions");
                b.Navigation("Refunds");
            });
#pragma warning restore 612, 618
        }
    }
}
