// <auto-generated />
using System;
using D.Ceylon.Modules.Bookings.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace D.Ceylon.Modules.Bookings.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BookingsDbContext))]
    [Migration("20260728110000_AddBookingWorkflow")]
    partial class AddBookingWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bookings")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("D.Ceylon.Modules.Bookings.Domain.Booking", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
                b.Property<string>("BookingReference").IsRequired().HasMaxLength(30).HasColumnName("booking_reference").HasColumnType("character varying(30)");
                b.Property<DateTimeOffset?>("CancelledAtUtc").HasColumnName("cancelled_at_utc").HasColumnType("timestamp with time zone");
                b.Property<string>("CancellationReason").HasMaxLength(500).HasColumnName("cancellation_reason").HasColumnType("character varying(500)");
                b.Property<DateTimeOffset?>("ConfirmedAtUtc").HasColumnName("confirmed_at_utc").HasColumnType("timestamp with time zone");
                b.Property<Guid>("ConcurrencyToken").IsConcurrencyToken().HasColumnName("concurrency_token").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnName("created_at_utc").HasColumnType("timestamp with time zone");
                b.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnName("currency").HasColumnType("character varying(3)");
                b.Property<string>("CustomerNotes").HasMaxLength(2000).HasColumnName("customer_notes").HasColumnType("character varying(2000)");
                b.Property<Guid>("CustomerId").HasColumnName("customer_id").HasColumnType("uuid");
                b.Property<string>("InternalNotes").HasMaxLength(2000).HasColumnName("internal_notes").HasColumnType("character varying(2000)");
                b.Property<string>("ItineraryTitle").IsRequired().HasMaxLength(200).HasColumnName("itinerary_title").HasColumnType("character varying(200)");
                b.Property<Guid?>("OrganisationId").HasColumnName("organisation_id").HasColumnType("uuid");
                b.Property<decimal>("PaidAmount").HasPrecision(18, 2).HasColumnName("paid_amount").HasColumnType("numeric(18,2)");
                b.Property<Guid>("QuoteId").HasColumnName("quote_id").HasColumnType("uuid");
                b.Property<Guid>("QuoteVersionId").HasColumnName("quote_version_id").HasColumnType("uuid");
                b.Property<string>("Status").IsRequired().HasMaxLength(40).HasColumnName("status").HasColumnType("character varying(40)");
                b.Property<decimal>("TotalAmount").HasPrecision(18, 2).HasColumnName("total_amount").HasColumnType("numeric(18,2)");
                b.Property<DateOnly>("TravelEndDate").HasColumnName("travel_end_date").HasColumnType("date");
                b.Property<DateOnly>("TravelStartDate").HasColumnName("travel_start_date").HasColumnType("date");
                b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnName("updated_at_utc").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("BookingReference").IsUnique().HasDatabaseName("ux_bookings_reference");
                b.HasIndex("QuoteId").IsUnique().HasDatabaseName("ux_bookings_quote");
                b.HasIndex("CustomerId", "Status", "UpdatedAtUtc").HasDatabaseName("ix_bookings_customer_status_updated");
                b.HasIndex("OrganisationId", "Status", "UpdatedAtUtc").HasDatabaseName("ix_bookings_organisation_status_updated");
                b.HasIndex("Status", "TravelStartDate").HasDatabaseName("ix_bookings_status_start_date");
                b.ToTable("bookings", "bookings", t =>
                {
                    t.HasCheckConstraint("ck_bookings_amounts", "total_amount >= 0 AND paid_amount >= 0 AND paid_amount <= total_amount + 0.01");
                    t.HasCheckConstraint("ck_bookings_currency", "currency IN ('EUR','GBP','LKR','USD')");
                    t.HasCheckConstraint("ck_bookings_dates", "travel_end_date >= travel_start_date");
                    t.HasCheckConstraint("ck_bookings_status", "status IN ('pending-confirmation','confirmed','partially-paid','paid','in-progress','completed','cancellation-requested','cancelled','refunded')");
                });
            });

            modelBuilder.Entity("D.Ceylon.Modules.Bookings.Domain.BookingItem", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
                b.Property<Guid>("BookingId").HasColumnName("booking_id").HasColumnType("uuid");
                b.Property<Guid>("ConcurrencyToken").IsConcurrencyToken().HasColumnName("concurrency_token").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnName("created_at_utc").HasColumnType("timestamp with time zone");
                b.Property<string>("Description").HasMaxLength(1000).HasColumnName("description").HasColumnType("character varying(1000)");
                b.Property<decimal>("LineTotal").HasPrecision(18, 2).HasColumnName("line_total").HasColumnType("numeric(18,2)");
                b.Property<int>("Position").HasColumnName("position").HasColumnType("integer");
                b.Property<decimal>("Quantity").HasPrecision(12, 2).HasColumnName("quantity").HasColumnType("numeric(12,2)");
                b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnName("title").HasColumnType("character varying(200)");
                b.Property<decimal>("UnitAmount").HasPrecision(18, 2).HasColumnName("unit_amount").HasColumnType("numeric(18,2)");
                b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnName("updated_at_utc").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("BookingId", "Position").IsUnique().HasDatabaseName("ux_booking_items_order");
                b.ToTable("booking_items", "bookings", t =>
                {
                    t.HasCheckConstraint("ck_booking_items_amounts", "unit_amount >= 0 AND line_total >= 0");
                    t.HasCheckConstraint("ck_booking_items_quantity", "quantity > 0 AND quantity <= 1000");
                });
            });

            modelBuilder.Entity("D.Ceylon.Modules.Bookings.Domain.Invoice", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
                b.Property<decimal>("AdjustmentTotal").HasPrecision(18, 2).HasColumnName("adjustment_total").HasColumnType("numeric(18,2)");
                b.Property<Guid>("BookingId").HasColumnName("booking_id").HasColumnType("uuid");
                b.Property<Guid>("ConcurrencyToken").IsConcurrencyToken().HasColumnName("concurrency_token").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnName("created_at_utc").HasColumnType("timestamp with time zone");
                b.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnName("currency").HasColumnType("character varying(3)");
                b.Property<string>("DocumentKey").HasMaxLength(500).HasColumnName("document_key").HasColumnType("character varying(500)");
                b.Property<DateTimeOffset?>("DueAtUtc").HasColumnName("due_at_utc").HasColumnType("timestamp with time zone");
                b.Property<decimal>("GrandTotal").HasPrecision(18, 2).HasColumnName("grand_total").HasColumnType("numeric(18,2)");
                b.Property<string>("InvoiceNumber").IsRequired().HasMaxLength(30).HasColumnName("invoice_number").HasColumnType("character varying(30)");
                b.Property<DateTimeOffset?>("IssuedAtUtc").HasColumnName("issued_at_utc").HasColumnType("timestamp with time zone");
                b.Property<DateTimeOffset?>("PaidAtUtc").HasColumnName("paid_at_utc").HasColumnType("timestamp with time zone");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnName("status").HasColumnType("character varying(20)");
                b.Property<decimal>("Subtotal").HasPrecision(18, 2).HasColumnName("subtotal").HasColumnType("numeric(18,2)");
                b.Property<decimal>("TaxTotal").HasPrecision(18, 2).HasColumnName("tax_total").HasColumnType("numeric(18,2)");
                b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnName("updated_at_utc").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("InvoiceNumber").IsUnique().HasDatabaseName("ux_invoices_number");
                b.HasIndex("BookingId", "Status").HasDatabaseName("ix_invoices_booking_status");
                b.ToTable("invoices", "bookings", t =>
                {
                    t.HasCheckConstraint("ck_invoices_amounts", "subtotal >= 0 AND tax_total >= 0 AND grand_total >= 0");
                    t.HasCheckConstraint("ck_invoices_currency", "currency IN ('EUR','GBP','LKR','USD')");
                    t.HasCheckConstraint("ck_invoices_status", "status IN ('draft','issued','paid','void')");
                });
            });

            modelBuilder.Entity("D.Ceylon.Modules.Bookings.Domain.Voucher", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
                b.Property<Guid>("BookingId").HasColumnName("booking_id").HasColumnType("uuid");
                b.Property<Guid>("ConcurrencyToken").IsConcurrencyToken().HasColumnName("concurrency_token").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnName("created_at_utc").HasColumnType("timestamp with time zone");
                b.Property<string>("Description").HasMaxLength(2000).HasColumnName("description").HasColumnType("character varying(2000)");
                b.Property<string>("DocumentKey").HasMaxLength(500).HasColumnName("document_key").HasColumnType("character varying(500)");
                b.Property<DateTimeOffset>("IssuedAtUtc").HasColumnName("issued_at_utc").HasColumnType("timestamp with time zone");
                b.Property<DateTimeOffset?>("RedeemedAtUtc").HasColumnName("redeemed_at_utc").HasColumnType("timestamp with time zone");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnName("status").HasColumnType("character varying(20)");
                b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnName("title").HasColumnType("character varying(200)");
                b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnName("updated_at_utc").HasColumnType("timestamp with time zone");
                b.Property<DateOnly>("ValidFrom").HasColumnName("valid_from").HasColumnType("date");
                b.Property<DateOnly>("ValidUntil").HasColumnName("valid_until").HasColumnType("date");
                b.Property<string>("VoucherCode").IsRequired().HasMaxLength(50).HasColumnName("voucher_code").HasColumnType("character varying(50)");
                b.HasKey("Id");
                b.HasIndex("VoucherCode").IsUnique().HasDatabaseName("ux_vouchers_code");
                b.HasIndex("BookingId", "Status").HasDatabaseName("ix_vouchers_booking_status");
                b.ToTable("vouchers", "bookings", t =>
                {
                    t.HasCheckConstraint("ck_vouchers_status", "status IN ('issued','redeemed','cancelled','expired')");
                    t.HasCheckConstraint("ck_vouchers_validity", "valid_until >= valid_from");
                });
            });

            modelBuilder.Entity("D.Ceylon.Modules.Bookings.Domain.BookingItem", b =>
            {
                b.HasOne("D.Ceylon.Modules.Bookings.Domain.Booking", null)
                    .WithMany("Items")
                    .HasForeignKey("BookingId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("D.Ceylon.Modules.Bookings.Domain.Invoice", b =>
            {
                b.HasOne("D.Ceylon.Modules.Bookings.Domain.Booking", null)
                    .WithMany("Invoices")
                    .HasForeignKey("BookingId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("D.Ceylon.Modules.Bookings.Domain.Voucher", b =>
            {
                b.HasOne("D.Ceylon.Modules.Bookings.Domain.Booking", null)
                    .WithMany("Vouchers")
                    .HasForeignKey("BookingId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("D.Ceylon.Modules.Bookings.Domain.Booking", b =>
            {
                b.Navigation("Items");
                b.Navigation("Invoices");
                b.Navigation("Vouchers");
            });
#pragma warning restore 612, 618
        }
    }
}
