// <auto-generated />
using System;
using D.Ceylon.Modules.CustomersTravellers.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace D.Ceylon.Modules.CustomersTravellers.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CustomersTravellersDbContext))]
    [Migration("20260728054220_AddCustomerRecords")]
    partial class AddCustomerRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("customers_travellers")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("D.Ceylon.Modules.CustomersTravellers.Domain.CustomerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("contact_phone");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("family_name");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("given_name");

                    b.Property<bool>("MarketingConsent")
                        .HasColumnType("boolean")
                        .HasColumnName("marketing_consent");

                    b.Property<string>("PreferredContactMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("preferred_contact_method");

                    b.Property<string>("PreferredLocale")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("preferred_locale");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ContactEmail")
                        .HasDatabaseName("ix_customer_profiles_contact_email");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_profiles_customer_id");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("ix_customer_profiles_updated_at");

                    b.ToTable("customer_profiles", "customers_travellers");
                });

            modelBuilder.Entity("D.Ceylon.Modules.CustomersTravellers.Domain.SavedItinerary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("PrimaryDestinationSlug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("primary_destination_slug");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateOnly?>("TravelEndDate")
                        .HasColumnType("date")
                        .HasColumnName("travel_end_date");

                    b.Property<DateOnly?>("TravelStartDate")
                        .HasColumnType("date")
                        .HasColumnName("travel_start_date");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryDestinationSlug")
                        .HasDatabaseName("ix_saved_itineraries_destination_slug");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("ix_saved_itineraries_updated_at");

                    b.HasIndex("CustomerId", "IsArchived", "UpdatedAtUtc")
                        .HasDatabaseName("ix_saved_itineraries_customer_archived_updated");

                    b.ToTable("saved_itineraries", "customers_travellers", t =>
                        {
                            t.HasCheckConstraint("ck_saved_itineraries_travel_dates", "travel_end_date IS NULL OR travel_start_date IS NULL OR travel_end_date >= travel_start_date");
                        });
                });

            modelBuilder.Entity("D.Ceylon.Modules.CustomersTravellers.Domain.Traveller", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessibilityNeeds")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("accessibility_needs");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DietaryNeeds")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("dietary_needs");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("emergency_contact_phone");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("family_name");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("given_name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_travellers_customer_id");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("ix_travellers_updated_at");

                    b.HasIndex("CustomerId", "FamilyName", "GivenName")
                        .HasDatabaseName("ix_travellers_customer_name");

                    b.ToTable("travellers", "customers_travellers");
                });

            modelBuilder.Entity("D.Ceylon.Modules.CustomersTravellers.Domain.WishlistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("ProductSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_slug");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("ix_wishlist_entries_updated_at");

                    b.HasIndex("CustomerId", "CreatedAtUtc")
                        .HasDatabaseName("ix_wishlist_entries_customer_created_at");

                    b.HasIndex("CustomerId", "ProductSlug")
                        .IsUnique()
                        .HasDatabaseName("ux_wishlist_entries_customer_product");

                    b.ToTable("wishlist_entries", "customers_travellers");
                });
#pragma warning restore 612, 618
        }
    }
}
