const modules = [
  ["products", "Products", "Catalogue product governance."],
  ["product-types", "Product types", "Structured product taxonomy."],
  ["categories", "Categories", "Catalogue classification."],
  ["collections", "Collections", "Collection editorial configuration."],
  ["destinations", "Destinations", "Destination editorial coordination."],
  ["experiences", "Experiences", "Experience catalogue oversight."],
  ["accommodation", "Accommodation", "Accommodation catalogue oversight."],
  ["transportation", "Transportation", "Transport and transfer foundations."],
  ["services", "Services", "Service catalogue foundations."],
  ["suppliers", "Suppliers", "Supplier directory review."],
  ["customers", "Customers", "Privacy-constrained customer support."],
  ["agents", "Agents", "Organisation-scoped agent oversight."],
  ["leads", "Leads", "Sales enquiry foundations."],
  ["quote-requests", "Quote requests", "Customer quote intake."],
  ["quotes", "Quotes", "Versioned commercial workflow."],
  ["bookings", "Bookings", "Accepted quote booking workflow."],
  ["payments", "Payments", "Reconciliation and payment state."],
  ["invoices", "Invoices", "Documented billing records."],
  ["arrivals", "Arrivals", "Arrival coordination foundation."],
  ["drivers", "Drivers", "Driver directory foundation."],
  ["guides", "Guides", "Guide directory foundation."],
  ["vehicles", "Vehicles", "Vehicle records foundation."],
  ["assignments", "Assignments", "Operational assignment foundation."],
  ["journal", "Journal", "Editorial content management."],
  ["media", "Media", "Editorial media metadata."],
  ["promotions", "Promotions", "Editorial promotion management."],
  ["users", "Users", "Identity account governance."],
  ["roles", "Roles", "Role and permission policy."],
  ["audit-logs", "Audit logs", "Security-sensitive activity review."],
  ["settings", "Settings", "Environment-managed configuration."],
  ["reports", "Reports", "Reporting foundation."],
] as const;

export const ADMIN_MODULES = modules.map(([slug, name, description]) => ({
  slug,
  name,
  description,
}));
